--- This is Dockerfile for creating chernovroman1984/user2 image (based on nginx:latest) ---

# Base image to build from Nginx (Latest)
FROM nginx:latest

# Author
LABEL maintainer="Chernov Roman <chernov.roman1984@gmail.com>"
